force-app/main/default/objects/Device__c/Device__c.object-meta.xml
<CustomObject>
    <label>Device</label>
    <nameField>
        <label>Device Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Device__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Devices</relationshipLabel>
    <relationshipName>Devices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Display__c.field-meta.xml
<CustomField>
    <fullName>Display__c</fullName>
    <label>Display</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Processor__c.field-meta.xml
<CustomField>
    <fullName>Processor__c</fullName>
    <label>Processor</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/RAM__c.field-meta.xml
<CustomField>
    <fullName>RAM__c</fullName>
    <label>RAM</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Storage__c.field-meta.xml
<CustomField>
    <fullName>Storage__c</fullName>
    <label>Storage</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TechnologyParkControllerTest.cls
@isTest
public  class TechnologyParkControllerTest {
    @testSetup
    private static void setupData() {
        Brand__c brand = new Brand__c(Name='Brand');
        insert brand;
        Device__c device1 = new Device__c();
        device1.Name = 'Device1';
        device1.Brand__c = brand.Id;
        device1.Processor__c = 'Processor';
        device1.Display__c = 'Display';
        device1.RAM__c = 4;
        device1.Storage__c = 64;
        device1.Price__c = 100;
        device1.Quantity__c = 123;
        insert device1;
    }

    @isTest public static void testGetAllBrands() {
        List<Brand__c> brands = new List<Brand__c>();
        brands = TechnologyParkController.getAllBrands();
        System.assertNotEquals(0, brands.size());
    }

    @isTest public static void testGetAllDevices() {
        List<Device__c> devices = new List<Device__c>();
        devices = TechnologyParkController.getAllDevices('All');
        System.assertNotEquals(0, devices.size());
        List<Brand__c> brands = [SELECT Id FROM Brand__c];
        devices = TechnologyParkController.getAllDevices(brands[0].Id);
        System.assertNotEquals(0, devices.size());
    }
}