force-app/main/default/objects/Device__c/Device__c.object-meta.xml
<CustomObject>
    <label>Device</label>
    <nameField>
        <label>Device Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Device__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Devices</relationshipLabel>
    <relationshipName>Devices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Display__c.field-meta.xml
<CustomField>
    <fullName>Display__c</fullName>
    <label>Display</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Processor__c.field-meta.xml
<CustomField>
    <fullName>Processor__c</fullName>
    <label>Processor</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/RAM__c.field-meta.xml
<CustomField>
    <fullName>RAM__c</fullName>
    <label>RAM</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Storage__c.field-meta.xml
<CustomField>
    <fullName>Storage__c</fullName>
    <label>Storage</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Devices</relationshipLabel>
    <relationshipName>Devices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TechnologyParkController.cls
public with sharing class TechnologyParkController {
  @AuraEnabled(cacheable=true)
  public static List<Brand__c> getAllBrands(){
    try {
      // Use SOQL to query all brand record
      List<Brand__c> result = new List<Brand__c>();
      if(Schema.sObjectType.Brand__c.isAccessible()) {
        result = [SELECT Id, Name FROM Brand__c];
      }
      return result;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  @AuraEnabled(cacheable=true)
  public static List<Device__c> getAllDevices(String brandId){
    try {
      // Use SOQL to query all device record on brand Id
      List<Device__c> result = new List<Device__c>();
      if(Schema.sObjectType.Device__c.isAccessible()) {
        if(brandId.equals('All')) {
          result = [
            SELECT Id, Name, Brand__c, Brand__r.Name, Store__c, Processor__c, Display__c, RAM__c, Storage__c, Quantity__c, Price__c
            FROM Device__c
          ];
        } else {
          result = [
            SELECT Id, Name, Brand__c, Brand__r.Name, Store__c, Processor__c, Display__c, RAM__c, Storage__c, Quantity__c, Price__c
            FROM Device__c 
            WHERE Brand__c =: brandId
          ];
        }
      }
      return result;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}